services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.6
    hostname: zookeeper
    container_name: oplib_zookeeper
    ports:
      - "2182:2181"  # Ubah port host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
      - oplib-network

  kafka:
    image: confluentinc/cp-kafka:7.4.6
    hostname: kafka
    container_name: oplib_kafka
    ports:
      - "9093:9092"  # Ubah port host
      - "29094:29092"
      - "29095:29093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper
    networks:
      - oplib-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: oplib_kafka-ui
    ports:
      - "8071:8080"  # Ubah port host
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:19092
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - oplib-network

  postgres:
    container_name: oplib_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ndnRG@123
    ports:
      - "5433:5432"  # Ubah port host
    volumes:
      - oplib_postgresql:/var/lib/postgresql
      - oplib_postgresql_data:/var/lib/postgresql/data
    networks:
      - oplib-network

  pgadmin:
    container_name: oplib_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"  # Ubah port host
    networks:
      - oplib-network

networks:
  oplib-network:
    driver: bridge

volumes:
  oplib_postgresql:
  oplib_postgresql_data:
